# Site settings
title: Works by Khoa.
description: "A personal site to showcase projects by Khoa Truong."
baseurl: ""
url: ""
tagline: Everything's coming up roses.

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 6
paginate_path: '/project/page:num/'
permalink: /project/:title

sass:
    sass_dir: _sass
