# Site settings
title: Khoa.
description: "Personal site to showcase projects by Khoa Truong"
baseurl: ""
url: ""
tagline: On Display

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 6
paginate_path: '/project/page:num/'
permalink: /project/:title

sass:
    sass_dir: _sass
